# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/SWE_HW8',
                'doc_host': 'https://amj0851.github.io',
                'git_url': 'https://github.com/amj0851/SWE_HW8',
                'lib_path': 'SWE_HW8'},
  'syms': {'SWE_HW8.core': {'SWE_HW8.core.foo': ('core.html#foo', 'SWE_HW8/core.py')}}}